controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

  # config/routes.yaml

home:
  path: /
  controller: App\Controller\HomeController::index

producto_detalle:
  path: /producto/{id}
  controller: App\Controller\ProductoController::detalle

carrito:
  path: /carrito
  controller: App\Controller\CarritoController::index
